apiVersion: v1
kind: Service
metadata:
    name: ignite-dev
spec:
    ports:
    - name: “ignite-dev”
      targetPort: 8080
      port: 8080
      nodePort: 30253
      protocol: TCP
    selector:
       app: ignite-dev
    type: NodePort